In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [125]:
dataset = pd.read_csv('Placement_Data_Full_Class.csv')

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   

    degree_t workex  etest_p specialisation  mba_p      status    salary  
0   Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1   Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2  Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3   Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4  Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0

In [110]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder() 
dataset['gender']= label_encoder.fit_transform(dataset['gender']) 
dataset['gender'].unique() 

dataset['ssc_b']= label_encoder.fit_transform(dataset['ssc_b']) 
dataset['ssc_b'].unique() 

dataset['hsc_b']= label_encoder.fit_transform(dataset['hsc_b']) 
dataset['hsc_b'].unique() 

dataset['hsc_s']= label_encoder.fit_transform(dataset['hsc_s']) 
dataset['hsc_s'].unique() 

dataset['degree_t']= label_encoder.fit_transform(dataset['degree_t']) 
dataset['degree_t'].unique() 

dataset['workex']= label_encoder.fit_transform(dataset['workex']) 
dataset['workex'].unique() 

dataset['specialisation']= label_encoder.fit_transform(dataset['specialisation']) 
dataset['specialisation'].unique() 

dataset['status']= label_encoder.fit_transform(dataset['status']) 
dataset['status'].unique()

array([1, 0])

In [111]:
x = dataset.iloc[:, 1:13].values

array([[ 1.  , 67.  ,  1.  , ..., 55.  ,  1.  , 58.8 ],
       [ 1.  , 79.33,  0.  , ..., 86.5 ,  0.  , 66.28],
       [ 1.  , 65.  ,  0.  , ..., 75.  ,  0.  , 57.8 ],
       ...,
       [ 1.  , 67.  ,  1.  , ..., 59.  ,  0.  , 69.72],
       [ 0.  , 74.  ,  1.  , ..., 70.  ,  1.  , 60.23],
       [ 1.  , 62.  ,  0.  , ..., 89.  ,  1.  , 60.22]])

In [112]:
y=dataset.iloc[:,13].values
y

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [113]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 1)

In [114]:
x_train

array([[ 0.  , 63.4 ,  1.  , ..., 58.06,  1.  , 69.28],
       [ 0.  , 85.  ,  1.  , ..., 92.  ,  0.  , 68.03],
       [ 0.  , 43.  ,  0.  , ..., 92.66,  1.  , 62.92],
       ...,
       [ 1.  , 84.86,  1.  , ..., 95.5 ,  0.  , 68.53],
       [ 1.  , 65.  ,  0.  , ..., 56.  ,  0.  , 56.94],
       [ 0.  , 79.  ,  0.  , ..., 58.  ,  1.  , 55.47]])

In [115]:
x_test

array([[ 1.  , 61.  ,  0.  , 82.  ,  0.  ,  1.  , 69.  ,  0.  ,  0.  ,
        84.  ,  0.  , 58.31],
       [ 1.  , 83.33,  0.  , 78.  ,  1.  ,  1.  , 61.  ,  0.  ,  1.  ,
        88.56,  0.  , 71.55],
       [ 1.  , 61.08,  1.  , 50.  ,  1.  ,  2.  , 54.  ,  2.  ,  0.  ,
        71.  ,  0.  , 65.69],
       [ 1.  , 82.  ,  1.  , 90.  ,  1.  ,  1.  , 83.  ,  0.  ,  0.  ,
        80.  ,  1.  , 73.52],
       [ 1.  , 54.4 ,  0.  , 61.12,  0.  ,  1.  , 56.2 ,  0.  ,  0.  ,
        67.  ,  1.  , 62.65],
       [ 0.  , 87.  ,  1.  , 65.  ,  1.  ,  2.  , 81.  ,  0.  ,  1.  ,
        88.  ,  0.  , 72.78],
       [ 1.  , 52.6 ,  0.  , 65.58,  1.  ,  2.  , 72.11,  2.  ,  0.  ,
        57.6 ,  0.  , 56.66],
       [ 0.  , 75.4 ,  1.  , 60.5 ,  0.  ,  2.  , 84.  ,  2.  ,  0.  ,
        98.  ,  0.  , 65.25],
       [ 1.  , 85.8 ,  0.  , 73.6 ,  0.  ,  1.  , 73.3 ,  0.  ,  0.  ,
        96.8 ,  0.  , 55.5 ],
       [ 0.  , 67.  ,  0.  , 53.  ,  0.  ,  2.  , 65.  ,  2.  ,  0.  ,
        64.  ,  1.  

In [116]:
y_test

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1])

In [117]:
y_train

array([0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1])

In [118]:
dataset.head()

sl_no  gender  ssc_p  ssc_b  hsc_p  hsc_b  hsc_s  degree_p  degree_t  \
0      1       1  67.00      1  91.00      1      1     58.00         2   
1      2       1  79.33      0  78.33      1      2     77.48         2   
2      3       1  65.00      0  68.00      0      0     64.00         0   
3      4       1  56.00      0  52.00      0      2     52.00         2   
4      5       1  85.80      0  73.60      0      1     73.30         0   

   workex  etest_p  specialisation  mba_p  status    salary  
0       0     55.0               1  58.80       1  270000.0  
1       1     86.5               0  66.28       1  200000.0  
2       0     75.0               0  57.80       1  250000.0  
3       0     66.0               1  59.43       0       NaN  
4       0     96.8               0  55.50       1  425000.0

In [119]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
classifier.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [120]:
print(classifier.predict(([[1,67,1,91,1,1,58,2,0,55,1,58]])))

[1]


In [121]:
y_pred = classifier.predict(x_test)

In [122]:
y_pred

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1])

In [123]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[12  5]
 [ 1 36]]


0.8888888888888888